stages:
  preprocess:
    cmd: python src/data_loader.py --input data/MachineLearningRating_v3.txt --output data/insurance_data.csv
    deps:
      - src/data_loader.py
      - data/MachineLearningRating_v3.txt
    outs:
      - data/insurance_data.csv
